spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymall?characterEncodeing=UTF-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity=MYSQL: